language: node_js
node_js:
  - stable
cache: npm
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist
  fqdn: "bestony.com"
  name: "Bestony on Travis"
  on:
    branch: master
